In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data=pd.read_csv('files/ex.csv',encoding='cp1252')
data.head()

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
1,Aankh Marey,"Kumar Sanu, Mika Singh, Neha Kakkar",BollywoodDance,Simmba,8.8/10
2,Coca Cola,"Neha Kakkar, Tony Kakkar",BollywoodDanceRomantic,Luka Chuppi,9.0/10
3,Apna Time Aayega,Ranveer Singh,BollywoodDance,Gully Boy,9.7/10
4,Mungda,"Jyotica Tangri, Shaan, Subhro Ganguly",BollywoodDance,Total Dhamaal,9.1/10
5,Tere Bin,"Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi",BollywoodRomantic,Simmba,9.2/10

In [3]:
data.columns

Index(['Song-Name', 'Singer/Artists', 'Genre', 'Album/Movie', 'User-Rating'], dtype='object')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2420 entries, 1 to 2420
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Song-Name       2420 non-null   object
 1   Singer/Artists  2410 non-null   object
 2   Genre           2420 non-null   object
 3   Album/Movie     2417 non-null   object
 4   User-Rating     2420 non-null   object
dtypes: object(5)
memory usage: 113.4+ KB

In [5]:
data.describe()

       Song-Name Singer/Artists           Genre Album/Movie User-Rating
count       2420           2410            2420        2417        2420
unique      2337           1214              21         902          38
top        Naina  Mohammed Rafi  BollywoodDance      Devdas      9.4/10
freq           3             55            1228          10         281

In [6]:
data.shape

(2420, 5)

In [7]:
data.isnull().sum()

Song-Name          0
Singer/Artists    10
Genre              0
Album/Movie        3
User-Rating        0
dtype: int64

In [8]:
data.dropna(inplace=True)

In [9]:
data.isnull().sum()

Song-Name         0
Singer/Artists    0
Genre             0
Album/Movie       0
User-Rating       0
dtype: int64

In [10]:
data.shape

(2407, 5)

In [11]:
data.duplicated().sum()

16

In [12]:
data.drop_duplicates(inplace=True)

In [13]:
data.shape

(2391, 5)

In [14]:
data.sample()

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
1254,Khulke Dulke,"Gippy Grewal, Harshdeep Kaur",BollywoodDance,Befikre,9.0/10

In [15]:
def rating(a):
    return float(a[:-3])

In [16]:
rating('9.6/10')

9.6

In [17]:
data['User-Rating'].unique()

array(['8.8/10', '9.0/10', '9.7/10', '9.1/10', '9.2/10', '9.5/10',
       '9.6/10', '8.4/10', '8.6/10', '9.4/10', '8.7/10', '9.3/10',
       '8.5/10', '8.9/10', '8.1/10', '7.7/10', '9.8/10', '6.8/10',
       '8.2/10', '9.9/10', '8.3/10', '7.2/10', '7.6/10', '7.5/10',
       '7.9/10', '7.3/10', '7.4/10', '7.8/10', '8.0/10', '7.0/10',
       '7.1/10', '6.9/10', '6.3/10', '5.8/10', '6.4/10', '10-Oct',
       '09-Oct', '6.6/10'], dtype=object)

In [18]:
data['User-Rating'].replace({'10-Oct': '7.0/10', "09-Oct":"7.0/10"}, inplace=True)

In [19]:
data["User-Rating"] = data["User-Rating"].apply(rating)

In [20]:
data.sample()

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
943,Rajj Rajj Ke,"Sonakshi Sinha, Vishal Dadlani",BollywoodMotivational,Akira,8.9

In [21]:
data["Genre"].unique()

array(['BollywoodDance', 'BollywoodDanceRomantic', 'BollywoodRomantic',
       'Bollywood', 'BollywoodDevotional', 'BollywoodRomanticSad',
       'BollywoodDanceSad', 'BollywoodSad', 'BollywoodMotivational',
       'BollywoodRomance', 'BollywoodSensual', 'BollywoodPatriotic',
       'BollywoodRomanticSadSensual', 'BollywoodRomanticSensual',
       'BollywoodDancePatriotic', 'BollywoodMotivationalPatriotic',
       'BollywoodDanceSensual', 'BollywoodDevotionalSad',
       'BollywoodDanceMotivationalPatriotic', 'BollywoodPatrioticSad'],
      dtype=object)

In [22]:
data["interest"]=data['Genre'] +"^"+ data['Singer/Artists']+"^"+data['Album/Movie']
data.sample()

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating,interest
261,Aaj Zid,Arijit Singh,BollywoodSensual,Aksar 2,9.1,BollywoodSensual^Arijit Singh^Aksar 2

In [23]:
def splitter(s):
    s = s.lower()
    return s.split('^')

In [24]:
data['interest']=data['interest'].apply(splitter)

In [25]:
data.sample()

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating,interest
1078,Hum Tumhare Hain Sanam,"Anuradha Paudwal, Udit Narayan",BollywoodRomantic,Hum Tumhare Hain Sanam,8.7,"[bollywoodromantic, anuradha paudwal, udit nar..."

In [26]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [27]:
def stem(lst):
    word = []

    for i in lst:
        word.append(ps.stem(i))
    
    return " ".join(word)

In [28]:
data["interest"] = data["interest"].apply(stem)
data.sample()

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating,interest
1282,Dhat Teri Ki,"Aditi Singh Sharma, Sanam Puri",BollywoodDance,Dhat Teri Ki,9.5,"bollywoodd aditi singh sharma, sanam puri dhat..."

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [30]:
vectors = cv.fit_transform(data["interest"]).toarray()

In [31]:
vectors.shape

(2391, 2138)

In [32]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
cv.get_stop_words()

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides',
           'between',
           'beyond',
           'bill',
           'both',
           'bottom',
           'but',
           'by',
           'call',
           'can',
           'cannot',
           'cant',
           'co',
           'con',
           'could',
           'couldnt',
           'cry',
           'de',
           'describe',
           'detail',
           'do',
           'done',
           'down',
           'due',
           'during',
           'each',
           'eg',
           'eight',
           'either',
           'eleven',
           'else',
           'elsewhere',
           'empty',
           'enough',
           'etc',
           'even',
           'ever',
           'every',
           'everyone',
           'everything',
           'everywhere',
           'except',
           'few',
           'fifteen',
           'fifty',
           'fill',
           'find',
           'fire',
           'first',
           'five',
           'for',
           'former',
           'formerly',
           'forty',
           'found',
           'four',
           'from',
           'front',
           'full',
           'further',
           'get',
           'give',
           'go',
           'had',
           'has',
           'hasnt',
           'have',
           'he',
           'hence',
           'her',
           'here',
           'hereafter',
           'hereby',
           'herein',
           'hereupon',
           'hers',
           'herself',
           'him',
           'himself',
           'his',
           'how',
           'however',
           'hundred',
           'i',
           'ie',
           'if',
           'in',
           'inc',
           'indeed',
           'interest',
           'into',
           'is',
           'it',
           'its',
           'itself',
           'keep',
           'last',
           'latter',
           'latterly',
           'least',
           'less',
           'ltd',
           'made',
           'many',
           'may',
           'me',
           'meanwhile',
           'might',
           'mill',
           'mine',
           'more',
           'moreover',
           'most',
           'mostly',
           'move',
           'much',
           'must',
           'my',
           'myself',
           'name',
           'namely',
           'neither',
           'never',
           'nevertheless',
           'next',
           'nine',
           'no',
           'nobody',
           'none',
           'noone',
           'nor',
           'not',
           'nothing',
           'now',
           'nowhere',
           'of',
           'off',
           'often',
           'on',
           'once',
           'one',
           'only',
           'onto',
           'or',
           'other',
           'others',
           'otherwise',
           'our',
           'ours',
           'ourselves',
           'out',
           'over',
           'own',
           'part',
           'per',
           'perhaps',
           'please',
           'put',
           'rather',
           're',
           'same',
           'see',
           'seem',
           'seemed',
           'seeming',
           'seems',
           'serious',
           'several',
           'she',
           'should',
           'show',
           'side',
           'since',
           'sincere',
           'six',
           'sixty',
           'so',
           'some',
           'somehow',
           'someone',
           'something',
           'sometime',
           'sometimes',
           'somewhere',
           'still',
           'such',
           'system',
           'take',
           'ten',
           'than',
           'that',
           'the',
           'their',
           'them',
           'themselves',
           'then',
           'thence',
           'there',
           'thereafter',
           'thereby',
           'therefore',
           'therein',
           'thereupon',
           'these',
           'they',
           'thick',
           'thin',
           'third',
           'this',
           'those',
           'though',
           'three',
           'through',
           'throughout',
           'thru',
           'thus',
           'to',
           'together',
           'too',
           'top',
           'toward',
           'towards',
           'twelve',
           'twenty',
           'two',
           'un',
           'under',
           'until',
           'up',
           'upon',
           'us',
           'very',
           'via',
           'was',
           'we',
           'well',
           'were',
           'what',
           'whatever',
           'when',
           'whence',
           'whenever',
           'where',
           'whereafter',
           'whereas',
           'whereby',
           'wherein',
           'whereupon',
           'wherever',
           'whether',
           'which',
           'while',
           'whither',
           'who',
           'whoever',
           'whole',
           'whom',
           'whose',
           'why',
           'will',
           'with',
           'within',
           'without',
           'would',
           'yet',
           'you',
           'your',
           'yours',
           'yourself',
           'yourselves'})

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
similarity = cosine_similarity(vectors)

In [36]:
similarity[0]

array([1.        , 0.35355339, 0.31622777, ..., 0.14433757, 0.14433757,
       0.14433757])

In [37]:
similarity.shape

(2391, 2391)

In [38]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])

[(0, 0.9999999999999998),
 (136, 0.5773502691896258),
 (5, 0.5303300858899106),
 (34, 0.5303300858899106),
 (540, 0.5303300858899106),
 (606, 0.5303300858899106),
 (919, 0.5303300858899106),
 (1388, 0.5303300858899106),
 (2272, 0.5303300858899106),
 (54, 0.4999999999999999),
 (1873, 0.4999999999999999),
 (1823, 0.49029033784546006),
 (269, 0.47434164902525683),
 (363, 0.47434164902525683),
 (465, 0.47434164902525683),
 (587, 0.47434164902525683),
 (1600, 0.47434164902525683),
 (1931, 0.47434164902525683),
 (2145, 0.47434164902525683),
 (2358, 0.47434164902525683),
 (655, 0.4714045207910316),
 (2125, 0.4714045207910316),
 (302, 0.4472135954999579),
 (309, 0.4472135954999579),
 (400, 0.4472135954999579),
 (1877, 0.4472135954999579),
 (1966, 0.4472135954999579),
 (181, 0.44194173824159216),
 (19, 0.4330127018922194),
 (40, 0.4330127018922194),
 (115, 0.4330127018922194),
 (117, 0.4330127018922194),
 (142, 0.4330127018922194),
 (184, 0.4330127018922194),
 (343, 0.4330127018922194),
 (371, 0.4330127018922194),
 (375, 0.4330127018922194),
 (406, 0.4330127018922194),
 (496, 0.4330127018922194),
 (513, 0.4330127018922194),
 (581, 0.4330127018922194),
 (648, 0.4330127018922194),
 (696, 0.4330127018922194),
 (820, 0.4330127018922194),
 (1054, 0.4330127018922194),
 (1078, 0.4330127018922194),
 (1241, 0.4330127018922194),
 (1381, 0.4330127018922194),
 (1508, 0.4330127018922194),
 (1649, 0.4330127018922194),
 (1782, 0.4330127018922194),
 (1815, 0.4330127018922194),
 (1957, 0.4330127018922194),
 (195, 0.408248290463863),
 (11, 0.40089186286863654),
 (35, 0.40089186286863654),
 (88, 0.40089186286863654),
 (241, 0.40089186286863654),
 (262, 0.40089186286863654),
 (600, 0.40089186286863654),
 (673, 0.40089186286863654),
 (1098, 0.40089186286863654),
 (1111, 0.40089186286863654),
 (1901, 0.40089186286863654),
 (2142, 0.40089186286863654),
 (2214, 0.40089186286863654),
 (2380, 0.40089186286863654),
 (6, 0.3749999999999999),
 (13, 0.3749999999999999),
 (25, 0.3749999999999999),
 (312, 0.3749999999999999),
 (716, 0.3749999999999999),
 (758, 0.3749999999999999),
 (1173, 0.3749999999999999),
 (1410, 0.3749999999999999),
 (1436, 0.3749999999999999),
 (1690, 0.3749999999999999),
 (1082, 0.36514837167011066),
 (1128, 0.36514837167011066),
 (1, 0.35355339059327373),
 (46, 0.35355339059327373),
 (51, 0.35355339059327373),
 (106, 0.35355339059327373),
 (108, 0.35355339059327373),
 (118, 0.35355339059327373),
 (169, 0.35355339059327373),
 (194, 0.35355339059327373),
 (244, 0.35355339059327373),
 (276, 0.35355339059327373),
 (313, 0.35355339059327373),
 (315, 0.35355339059327373),
 (434, 0.35355339059327373),
 (500, 0.35355339059327373),
 (608, 0.35355339059327373),
 (622, 0.35355339059327373),
 (636, 0.35355339059327373),
 (664, 0.35355339059327373),
 (746, 0.35355339059327373),
 (773, 0.35355339059327373),
 (840, 0.35355339059327373),
 (883, 0.35355339059327373),
 (947, 0.35355339059327373),
 (1117, 0.35355339059327373),
 (1120, 0.35355339059327373),
 (1279, 0.35355339059327373),
 (1309, 0.35355339059327373),
 (1396, 0.35355339059327373),
 (1530, 0.35355339059327373),
 (1543, 0.35355339059327373),
 (1631, 0.35355339059327373),
 (1648, 0.35355339059327373),
 (1725, 0.35355339059327373),
 (1809, 0.35355339059327373),
 (1970, 0.35355339059327373),
 (2028, 0.35355339059327373),
 (2031, 0.35355339059327373),
 (2061, 0.35355339059327373),
 (2066, 0.35355339059327373),
 (2081, 0.35355339059327373),
 (2114, 0.35355339059327373),
 (2155, 0.35355339059327373),
 (41, 0.33541019662496846),
 (1033, 0.33541019662496846),
 (1680, 0.33541019662496846),
 (2169, 0.33541019662496846),
 (2308, 0.33541019662496846),
 (39, 0.3198010745334156),
 (49, 0.3198010745334156),
 (125, 0.3198010745334156),
 (137, 0.3198010745334156),
 (386, 0.3198010745334156),
 (571, 0.3198010745334156),
 (585, 0.3198010745334156),
 (848, 0.3198010745334156),
 (1261, 0.3198010745334156),
 (2, 0.3162277660168379),
 (7, 0.3162277660168379),
 (15, 0.3162277660168379),
 (224, 0.3162277660168379),
 (589, 0.3162277660168379),
 (593, 0.3162277660168379),
 (1198, 0.3162277660168379),
 (1384, 0.3162277660168379),
 (1401, 0.3162277660168379),
 (1475, 0.3162277660168379),
 (1479, 0.3162277660168379),
 (1590, 0.3162277660168379),
 (1790, 0.3162277660168379),
 (1814, 0.3162277660168379),
 (1819, 0.3162277660168379),
 (2041, 0.3162277660168379),
 (2245, 0.3162277660168379),
 (2340, 0.3162277660168379),
 (156, 0.30618621784789724),
 (449, 0.30618621784789724),
 (607, 0.30618621784789724),
 (1216, 0.30618621784789724),
 (516, 0.294174202707276),
 (131, 0.2886751345948129),
 (202, 0.2886751345948129),
 (220, 0.2886751345948129),
 (300, 0.2886751345948129),
 (390, 0.2886751345948129),
 (407, 0.2886751345948129),
 (425, 0.2886751345948129),
 (435, 0.2886751345948129),
 (450, 0.2886751345948129),
 (453, 0.2886751345948129),
 (466, 0.2886751345948129),
 (505, 0.2886751345948129),
 (517, 0.2886751345948129),
 (533, 0.2886751345948129),
 (552, 0.2886751345948129),
 (555, 0.2886751345948129),
 (565, 0.2886751345948129),
 (582, 0.2886751345948129),
 (599, 0.2886751345948129),
 (601, 0.2886751345948129),
 (682, 0.2886751345948129),
 (722, 0.2886751345948129),
 (766, 0.2886751345948129),
 (791, 0.2886751345948129),
 (833, 0.2886751345948129),
 (854, 0.2886751345948129),
 (878, 0.2886751345948129),
 (960, 0.2886751345948129),
 (980, 0.2886751345948129),
 (1059, 0.2886751345948129),
 (1106, 0.2886751345948129),
 (1132, 0.2886751345948129),
 (1195, 0.2886751345948129),
 (1277, 0.2886751345948129),
 (1296, 0.2886751345948129),
 (1335, 0.2886751345948129),
 (1378, 0.2886751345948129),
 (1496, 0.2886751345948129),
 (1515, 0.2886751345948129),
 (1516, 0.2886751345948129),
 (1528, 0.2886751345948129),
 (1576, 0.2886751345948129),
 (1609, 0.2886751345948129),
 (1668, 0.2886751345948129),
 (1749, 0.2886751345948129),
 (1756, 0.2886751345948129),
 (1757, 0.2886751345948129),
 (1762, 0.2886751345948129),
 (1769, 0.2886751345948129),
 (1855, 0.2886751345948129),
 (1893, 0.2886751345948129),
 (1894, 0.2886751345948129),
 (1911, 0.2886751345948129),
 (1917, 0.2886751345948129),
 (2015, 0.2886751345948129),
 (2038, 0.2886751345948129),
 (2052, 0.2886751345948129),
 (2060, 0.2886751345948129),
 (2117, 0.2886751345948129),
 (2118, 0.2886751345948129),
 (2123, 0.2886751345948129),
 (2143, 0.2886751345948129),
 (2199, 0.2886751345948129),
 (2219, 0.2886751345948129),
 (2224, 0.2886751345948129),
 (2229, 0.2886751345948129),
 (2244, 0.2886751345948129),
 (2382, 0.2886751345948129),
 (239, 0.28347335475692037),
 (2014, 0.273861278752583),
 (47, 0.26726124191242434),
 (288, 0.26726124191242434),
 (433, 0.26726124191242434),
 (612, 0.26726124191242434),
 (635, 0.26726124191242434),
 (681, 0.26726124191242434),
 (714, 0.26726124191242434),
 (730, 0.26726124191242434),
 (788, 0.26726124191242434),
 (1045, 0.26726124191242434),
 (1061, 0.26726124191242434),
 (1089, 0.26726124191242434),
 (1093, 0.26726124191242434),
 (1140, 0.26726124191242434),
 (1181, 0.26726124191242434),
 (1192, 0.26726124191242434),
 (1207, 0.26726124191242434),
 (1312, 0.26726124191242434),
 (1406, 0.26726124191242434),
 (1414, 0.26726124191242434),
 (1467, 0.26726124191242434),
 (1478, 0.26726124191242434),
 (1520, 0.26726124191242434),
 (1653, 0.26726124191242434),
 (1675, 0.26726124191242434),
 (1730, 0.26726124191242434),
 (1739, 0.26726124191242434),
 (1780, 0.26726124191242434),
 (1821, 0.26726124191242434),
 (1853, 0.26726124191242434),
 (1862, 0.26726124191242434),
 (1863, 0.26726124191242434),
 (2087, 0.26726124191242434),
 (2130, 0.26726124191242434),
 (2141, 0.26726124191242434),
 (2148, 0.26726124191242434),
 (2324, 0.26726124191242434),
 (931, 0.25),
 (1395, 0.25),
 (10, 0.24999999999999994),
 (63, 0.24999999999999994),
 (123, 0.24999999999999994),
 (126, 0.24999999999999994),
 (231, 0.24999999999999994),
 (291, 0.24999999999999994),
 (360, 0.24999999999999994),
 (411, 0.24999999999999994),
 (482, 0.24999999999999994),
 (559, 0.24999999999999994),
 (584, 0.24999999999999994),
 (718, 0.24999999999999994),
 (751, 0.24999999999999994),
 (770, 0.24999999999999994),
 (822, 0.24999999999999994),
 (846, 0.24999999999999994),
 (860, 0.24999999999999994),
 (1085, 0.24999999999999994),
 (1108, 0.24999999999999994),
 (1118, 0.24999999999999994),
 (1158, 0.24999999999999994),
 (1187, 0.24999999999999994),
 (1229, 0.24999999999999994),
 (1295, 0.24999999999999994),
 (1409, 0.24999999999999994),
 (1460, 0.24999999999999994),
 (1511, 0.24999999999999994),
 (1525, 0.24999999999999994),
 (1608, 0.24999999999999994),
 (1750, 0.24999999999999994),
 (1865, 0.24999999999999994),
 (1884, 0.24999999999999994),
 (1961, 0.24999999999999994),
 (2001, 0.24999999999999994),
 (2039, 0.24999999999999994),
 (2072, 0.24999999999999994),
 (2093, 0.24999999999999994),
 (2094, 0.24999999999999994),
 (2172, 0.24999999999999994),
 (2193, 0.24999999999999994),
 (2222, 0.24999999999999994),
 (2261, 0.24999999999999994),
 (2367, 0.24999999999999994),
 (2369, 0.24999999999999994),
 (164, 0.2357022603955158),
 (232, 0.2357022603955158),
 (298, 0.2357022603955158),
 (351, 0.2357022603955158),
 (367, 0.2357022603955158),
 (442, 0.2357022603955158),
 (522, 0.2357022603955158),
 (595, 0.2357022603955158),
 (602, 0.2357022603955158),
 (627, 0.2357022603955158),
 (864, 0.2357022603955158),
 (909, 0.2357022603955158),
 (982, 0.2357022603955158),
 (1009, 0.2357022603955158),
 (1051, 0.2357022603955158),
 (1088, 0.2357022603955158),
 (1136, 0.2357022603955158),
 (1197, 0.2357022603955158),
 (1201, 0.2357022603955158),
 (1267, 0.2357022603955158),
 (1272, 0.2357022603955158),
 (1291, 0.2357022603955158),
 (1365, 0.2357022603955158),
 (1427, 0.2357022603955158),
 (1445, 0.2357022603955158),
 (1470, 0.2357022603955158),
 (1531, 0.2357022603955158),
 (1569, 0.2357022603955158),
 (1636, 0.2357022603955158),
 (1650, 0.2357022603955158),
 (1651, 0.2357022603955158),
 (1724, 0.2357022603955158),
 (1919, 0.2357022603955158),
 (1942, 0.2357022603955158),
 (2154, 0.2357022603955158),
 (2180, 0.2357022603955158),
 (2255, 0.2357022603955158),
 (2314, 0.2357022603955158),
 (68, 0.22360679774997896),
 (78, 0.22360679774997896),
 (203, 0.22360679774997896),
 (259, 0.22360679774997896),
 (354, 0.22360679774997896),
 (402, 0.22360679774997896),
 (428, 0.22360679774997896),
 (447, 0.22360679774997896),
 (488, 0.22360679774997896),
 (508, 0.22360679774997896),
 (548, 0.22360679774997896),
 (580, 0.22360679774997896),
 (702, 0.22360679774997896),
 (706, 0.22360679774997896),
 (740, 0.22360679774997896),
 (769, 0.22360679774997896),
 (838, 0.22360679774997896),
 (861, 0.22360679774997896),
 (906, 0.22360679774997896),
 (1332, 0.22360679774997896),
 (1333, 0.22360679774997896),
 (1483, 0.22360679774997896),
 (1655, 0.22360679774997896),
 (1827, 0.22360679774997896),
 (2007, 0.22360679774997896),
 (2013, 0.22360679774997896),
 (2150, 0.22360679774997896),
 (2294, 0.22360679774997896),
 (2307, 0.22360679774997896),
 (2313, 0.22360679774997896),
 (2384, 0.22360679774997896),
 (62, 0.21320071635561041),
 (261, 0.21320071635561041),
 (405, 0.21320071635561041),
 (521, 0.21320071635561041),
 (736, 0.21320071635561041),
 (737, 0.21320071635561041),
 (899, 0.21320071635561041),
 (1185, 0.21320071635561041),
 (1394, 0.21320071635561041),
 (1450, 0.21320071635561041),
 (1712, 0.21320071635561041),
 (1922, 0.21320071635561041),
 (2120, 0.21320071635561041),
 (2162, 0.21320071635561041),
 (82, 0.2041241452319315),
 (179, 0.2041241452319315),
 (240, 0.2041241452319315),
 (340, 0.2041241452319315),
 (511, 0.2041241452319315),
 (609, 0.2041241452319315),
 (717, 0.2041241452319315),
 (729, 0.2041241452319315),
 (816, 0.2041241452319315),
 (825, 0.2041241452319315),
 (958, 0.2041241452319315),
 (1002, 0.2041241452319315),
 (1024, 0.2041241452319315),
 (1026, 0.2041241452319315),
 (1027, 0.2041241452319315),
 (1046, 0.2041241452319315),
 (1076, 0.2041241452319315),
 (1119, 0.2041241452319315),
 (1190, 0.2041241452319315),
 (1236, 0.2041241452319315),
 (1252, 0.2041241452319315),
 (1304, 0.2041241452319315),
 (1379, 0.2041241452319315),
 (1405, 0.2041241452319315),
 (1514, 0.2041241452319315),
 (1542, 0.2041241452319315),
 (1563, 0.2041241452319315),
 (1575, 0.2041241452319315),
 (1614, 0.2041241452319315),
 (1621, 0.2041241452319315),
 (1634, 0.2041241452319315),
 (1682, 0.2041241452319315),
 (1767, 0.2041241452319315),
 (1786, 0.2041241452319315),
 (1843, 0.2041241452319315),
 (1866, 0.2041241452319315),
 (1875, 0.2041241452319315),
 (1937, 0.2041241452319315),
 (1976, 0.2041241452319315),
 (2022, 0.2041241452319315),
 (2035, 0.2041241452319315),
 (2053, 0.2041241452319315),
 (2074, 0.2041241452319315),
 (2173, 0.2041241452319315),
 (2183, 0.2041241452319315),
 (2284, 0.2041241452319315),
 (2303, 0.2041241452319315),
 (2338, 0.2041241452319315),
 (2386, 0.2041241452319315),
 (549, 0.19611613513818402),
 (1199, 0.19611613513818402),
 (1787, 0.19611613513818402),
 (807, 0.1889822365046136),
 (26, 0.18257418583505533),
 (8, 0.17677669529663687),
 (21, 0.17677669529663687),
 (23, 0.17677669529663687),
 (37, 0.17677669529663687),
 (42, 0.17677669529663687),
 (52, 0.17677669529663687),
 (55, 0.17677669529663687),
 (66, 0.17677669529663687),
 (73, 0.17677669529663687),
 (76, 0.17677669529663687),
 (80, 0.17677669529663687),
 (89, 0.17677669529663687),
 (119, 0.17677669529663687),
 (145, 0.17677669529663687),
 (162, 0.17677669529663687),
 (167, 0.17677669529663687),
 (173, 0.17677669529663687),
 (177, 0.17677669529663687),
 (210, 0.17677669529663687),
 (211, 0.17677669529663687),
 (258, 0.17677669529663687),
 (277, 0.17677669529663687),
 (287, 0.17677669529663687),
 (289, 0.17677669529663687),
 (296, 0.17677669529663687),
 (303, 0.17677669529663687),
 (305, 0.17677669529663687),
 (307, 0.17677669529663687),
 (326, 0.17677669529663687),
 (334, 0.17677669529663687),
 (338, 0.17677669529663687),
 (374, 0.17677669529663687),
 (376, 0.17677669529663687),
 (393, 0.17677669529663687),
 (421, 0.17677669529663687),
 (430, 0.17677669529663687),
 (454, 0.17677669529663687),
 (462, 0.17677669529663687),
 (481, 0.17677669529663687),
 (484, 0.17677669529663687),
 (489, 0.17677669529663687),
 (498, 0.17677669529663687),
 (510, 0.17677669529663687),
 (528, 0.17677669529663687),
 (563, 0.17677669529663687),
 (588, 0.17677669529663687),
 (591, 0.17677669529663687),
 (603, 0.17677669529663687),
 (620, 0.17677669529663687),
 (633, 0.17677669529663687),
 (641, 0.17677669529663687),
 (663, 0.17677669529663687),
 (672, 0.17677669529663687),
 (677, 0.17677669529663687),
 (689, 0.17677669529663687),
 (700, 0.17677669529663687),
 (713, 0.17677669529663687),
 (715, 0.17677669529663687),
 (725, 0.17677669529663687),
 (726, 0.17677669529663687),
 (780, 0.17677669529663687),
 (789, 0.17677669529663687),
 (792, 0.17677669529663687),
 (802, 0.17677669529663687),
 (804, 0.17677669529663687),
 (805, 0.17677669529663687),
 (815, 0.17677669529663687),
 (853, 0.17677669529663687),
 (869, 0.17677669529663687),
 (873, 0.17677669529663687),
 (874, 0.17677669529663687),
 (880, 0.17677669529663687),
 (881, 0.17677669529663687),
 (886, 0.17677669529663687),
 (900, 0.17677669529663687),
 (901, 0.17677669529663687),
 (932, 0.17677669529663687),
 (934, 0.17677669529663687),
 (939, 0.17677669529663687),
 (953, 0.17677669529663687),
 (973, 0.17677669529663687),
 (985, 0.17677669529663687),
 (997, 0.17677669529663687),
 (1003, 0.17677669529663687),
 (1005, 0.17677669529663687),
 (1038, 0.17677669529663687),
 (1043, 0.17677669529663687),
 (1057, 0.17677669529663687),
 (1080, 0.17677669529663687),
 (1086, 0.17677669529663687),
 (1090, 0.17677669529663687),
 (1125, 0.17677669529663687),
 (1161, 0.17677669529663687),
 (1167, 0.17677669529663687),
 (1170, 0.17677669529663687),
 (1200, 0.17677669529663687),
 (1238, 0.17677669529663687),
 (1247, 0.17677669529663687),
 (1250, 0.17677669529663687),
 (1254, 0.17677669529663687),
 (1255, 0.17677669529663687),
 (1259, 0.17677669529663687),
 (1260, 0.17677669529663687),
 (1274, 0.17677669529663687),
 (1287, 0.17677669529663687),
 (1289, 0.17677669529663687),
 (1293, 0.17677669529663687),
 (1297, 0.17677669529663687),
 (1315, 0.17677669529663687),
 (1318, 0.17677669529663687),
 (1320, 0.17677669529663687),
 (1323, 0.17677669529663687),
 (1353, 0.17677669529663687),
 (1355, 0.17677669529663687),
 (1360, 0.17677669529663687),
 (1364, 0.17677669529663687),
 (1367, 0.17677669529663687),
 (1377, 0.17677669529663687),
 (1383, 0.17677669529663687),
 (1386, 0.17677669529663687),
 (1398, 0.17677669529663687),
 (1399, 0.17677669529663687),
 (1433, 0.17677669529663687),
 (1443, 0.17677669529663687),
 (1457, 0.17677669529663687),
 (1462, 0.17677669529663687),
 (1498, 0.17677669529663687),
 (1499, 0.17677669529663687),
 (1509, 0.17677669529663687),
 (1529, 0.17677669529663687),
 (1538, 0.17677669529663687),
 (1559, 0.17677669529663687),
 (1580, 0.17677669529663687),
 (1594, 0.17677669529663687),
 (1639, 0.17677669529663687),
 (1642, 0.17677669529663687),
 (1663, 0.17677669529663687),
 (1667, 0.17677669529663687),
 (1684, 0.17677669529663687),
 (1696, 0.17677669529663687),
 (1699, 0.17677669529663687),
 (1707, 0.17677669529663687),
 (1726, 0.17677669529663687),
 (1800, 0.17677669529663687),
 (1824, 0.17677669529663687),
 (1829, 0.17677669529663687),
 (1830, 0.17677669529663687),
 (1833, 0.17677669529663687),
 (1861, 0.17677669529663687),
 (1881, 0.17677669529663687),
 (1905, 0.17677669529663687),
 (1933, 0.17677669529663687),
 (1935, 0.17677669529663687),
 (1939, 0.17677669529663687),
 (1946, 0.17677669529663687),
 (1952, 0.17677669529663687),
 (1983, 0.17677669529663687),
 (1988, 0.17677669529663687),
 (1990, 0.17677669529663687),
 (1998, 0.17677669529663687),
 (2003, 0.17677669529663687),
 (2017, 0.17677669529663687),
 (2058, 0.17677669529663687),
 (2062, 0.17677669529663687),
 (2079, 0.17677669529663687),
 (2097, 0.17677669529663687),
 (2103, 0.17677669529663687),
 (2105, 0.17677669529663687),
 (2110, 0.17677669529663687),
 (2111, 0.17677669529663687),
 (2129, 0.17677669529663687),
 (2134, 0.17677669529663687),
 (2136, 0.17677669529663687),
 (2138, 0.17677669529663687),
 (2156, 0.17677669529663687),
 (2161, 0.17677669529663687),
 (2182, 0.17677669529663687),
 (2194, 0.17677669529663687),
 (2215, 0.17677669529663687),
 (2218, 0.17677669529663687),
 (2227, 0.17677669529663687),
 (2259, 0.17677669529663687),
 (2281, 0.17677669529663687),
 (2282, 0.17677669529663687),
 (2310, 0.17677669529663687),
 (2311, 0.17677669529663687),
 (2315, 0.17677669529663687),
 (2317, 0.17677669529663687),
 (2329, 0.17677669529663687),
 (2341, 0.17677669529663687),
 (2347, 0.17677669529663687),
 (2385, 0.17677669529663687),
 (12, 0.15811388300841894),
 (27, 0.15811388300841894),
 (45, 0.15811388300841894),
 (59, 0.15811388300841894),
 (101, 0.15811388300841894),
 (120, 0.15811388300841894),
 (161, 0.15811388300841894),
 (176, 0.15811388300841894),
 (201, 0.15811388300841894),
 (251, 0.15811388300841894),
 (260, 0.15811388300841894),
 (272, 0.15811388300841894),
 (310, 0.15811388300841894),
 (369, 0.15811388300841894),
 (381, 0.15811388300841894),
 (389, 0.15811388300841894),
 (468, 0.15811388300841894),
 (504, 0.15811388300841894),
 (532, 0.15811388300841894),
 (568, 0.15811388300841894),
 (597, 0.15811388300841894),
 (618, 0.15811388300841894),
 (632, 0.15811388300841894),
 (638, 0.15811388300841894),
 (661, 0.15811388300841894),
 (687, 0.15811388300841894),
 (690, 0.15811388300841894),
 (694, 0.15811388300841894),
 (754, 0.15811388300841894),
 (806, 0.15811388300841894),
 (856, 0.15811388300841894),
 (890, 0.15811388300841894),
 (930, 0.15811388300841894),
 (943, 0.15811388300841894),
 (949, 0.15811388300841894),
 (991, 0.15811388300841894),
 (1017, 0.15811388300841894),
 (1019, 0.15811388300841894),
 (1031, 0.15811388300841894),
 (1081, 0.15811388300841894),
 (1103, 0.15811388300841894),
 (1113, 0.15811388300841894),
 (1134, 0.15811388300841894),
 (1135, 0.15811388300841894),
 (1163, 0.15811388300841894),
 (1206, 0.15811388300841894),
 (1221, 0.15811388300841894),
 (1224, 0.15811388300841894),

In [39]:
data[data['Song-Name']=='Main Kya Hoon']

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating,interest
1848,Main Kya Hoon,KK,BollywoodDance,Love Aj Kal,9.5,bollywoodd kk love aj k

In [40]:
data['Song-Name'].iloc[460]

'Saans'

In [41]:
def recommended(song):
    idx = data[data["Song-Name"] == song].index[0]
    corr = similarity[idx]
    rec = sorted(list(enumerate(corr)), reverse=True, key=lambda x: x[1])[1:16]

    for i in rec:
        print(data['Song-Name'].iloc[i[0]])

In [42]:
recommended('Main Kya Hoon')

Danka Bajega
Tere Ishq Ka Suroor
Saiyyan
Hum Tumhe Kaise Bataye
Raabta Tujhse Raha
Har Har Gange
Bum Mein Dum
Jaaneman Aah
Bola Har Har Har
Son Of Sardaar
Halo Re
Koshampa
Go Go Govinda (Reprise)
Zindagi Do Pal Ki
Tu Hi Meri Shab Hai

In [43]:

from pickle import dump

In [44]:
dump(data.to_dict(), open("songs.pkl", 'wb'))
dump(similarity, open("similarity.pkl", 'wb'))